#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# wallpaper 
feh --bg-fill ~/Pictures/Wallpapers/Rosepine/rosepine9.jpg

# Polybar
$HOME/.config/polybar/launch.sh &

# Dunst
killall dunst;notify-send BSPWM Restarted &

bspc monitor -d I II III IV V VI VII VIII IX
#bspc config border_width        2
bspc config window_gap          15
bspc config top_padding 0
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a discord desktop='^3' state=tiling follow=off
bspc rule -a obsidian desktop='^7' state=tiling follow=on
bspc rule -a spotify desktop='^4' sate=tliing follow=off
bspc rule -a zathura state=floating follow=on
bspc rule -a subl dekstop='^1' state=tiling follow=off

outer='0x171924x'
inner1='0x34304f'
inner2='0x1c1a2b'

trap 'bspc config border_width 0; kill -9 -$$' INT TERM

targets() {
    case $1 in
        focused) bspc query -N -n .local.focused.\!fullscreen;;
        normal)  bspc query -N -n .local.\!focused.\!fullscreen
    esac | grep -iv "$v"
}

bspc config border_width 10

draw() { chwb2 -I "$inner" -O "$outer" -i "5" -o "5" $* |:; }

#initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
    while read -r _; do
        [ "$v" ] || v='abcdefg'
        inner=$inner1 draw "$(targets focused)"
        inner=$inner2 draw "$(targets normal)"
        done
